# Generated by Django 4.1.7 on 2023-02-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsfeed', '0002_delete_newsfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsfeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photos', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
