# Generated by Django 4.1.7 on 2023-02-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0004_alter_newsfeed_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='Photos',
            field=models.TextField(),
        ),
    ]
