# Generated by Django 4.1.7 on 2023-02-21 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsfeed', '0006_userinfo_rename_photos_newsfeed_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.newsfeed')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
