# Generated by Django 4.2 on 2023-04-12 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsfeed', '0008_tags_newsfeed_likes_delete_likesphotos_newsfeed_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='tags',
            field=models.ManyToManyField(blank=True, to='newsfeed.tags'),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
