# Generated by Django 4.2 on 2023-04-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0012_alter_tags_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='owner',
        ),
    ]
