# Generated by Django 4.2 on 2023-04-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0014_tags_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_photo',
            field=models.TextField(),
        ),
    ]
