# Generated by Django 4.2 on 2023-06-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0016_newsfeed_description_alter_newsfeed_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsfeed',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='owner',
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
