# Generated by Django 4.2 on 2023-06-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0017_rename_user_id_newsfeed_user_remove_tags_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='newsfeed',
            name='photos',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='newsfeed_photos/')),
                ('newsfeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.newsfeed')),
            ],
        ),
    ]
