# Generated by Django 4.2 on 2023-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0018_remove_newsfeed_photo_remove_newsfeed_photos_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='newsfeed',
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='photos',
            field=models.ManyToManyField(blank=True, to='newsfeed.photo'),
        ),
    ]
