# Generated by Django 4.2 on 2023-06-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0020_alter_userinfo_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='photos',
            field=models.ManyToManyField(to='newsfeed.photo'),
        ),
    ]
