# Generated by Django 4.2 on 2023-06-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0023_userinfo_subscribers_userinfo_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='subscribers',
        ),
    ]
